/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Obada.Client.Client;
using Obada.Client.Api;
using Obada.Client.Model;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing ObitApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ObitApiTests
    {
        private ObitApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ObitApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObitApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' ObitApi
            //Assert.IsInstanceOf(typeof(ObitApi), instance);
        }

        
        /// <summary>
        /// Test Checksum
        /// </summary>
        [Test]
        public void ChecksumTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Obit obit = null;
            //var response = instance.Checksum(obit);
            //Assert.IsInstanceOf(typeof(Checksum), response, "response is Checksum");
        }
        
        /// <summary>
        /// Test GenerateId
        /// </summary>
        [Test]
        public void GenerateIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RequestObitId requestObitId = null;
            //var response = instance.GenerateId(requestObitId);
            //Assert.IsInstanceOf(typeof(ObitId), response, "response is ObitId");
        }
        
        /// <summary>
        /// Test Get
        /// </summary>
        [Test]
        public void GetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string obitDid = null;
            //var response = instance.Get(obitDid);
            //Assert.IsInstanceOf(typeof(Obit), response, "response is Obit");
        }
        
        /// <summary>
        /// Test History
        /// </summary>
        [Test]
        public void HistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string obitDid = null;
            //var response = instance.History(obitDid);
            //Assert.IsInstanceOf(typeof(InlineResponse200), response, "response is InlineResponse200");
        }
        
        /// <summary>
        /// Test Save
        /// </summary>
        [Test]
        public void SaveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Obit obit = null;
            //instance.Save(obit);
            
        }
        
        /// <summary>
        /// Test Search
        /// </summary>
        [Test]
        public void SearchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string q = null;
            //int? offset = null;
            //var response = instance.Search(q, offset);
            //Assert.IsInstanceOf(typeof(Obits), response, "response is Obits");
        }
        
    }

}
