/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing ClientObit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientObitTests
    {
        // TODO uncomment below to declare an instance variable for ClientObit
        //private ClientObit instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClientObit
            //instance = new ClientObit();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClientObit
        /// </summary>
        [Test]
        public void ClientObitInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ClientObit
            //Assert.IsInstanceOf(typeof(ClientObit), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ObitDid'
        /// </summary>
        [Test]
        public void ObitDidTest()
        {
            // TODO unit test for the property 'ObitDid'
        }
        /// <summary>
        /// Test the property 'Usn'
        /// </summary>
        [Test]
        public void UsnTest()
        {
            // TODO unit test for the property 'Usn'
        }
        /// <summary>
        /// Test the property 'OwnerDid'
        /// </summary>
        [Test]
        public void OwnerDidTest()
        {
            // TODO unit test for the property 'OwnerDid'
        }
        /// <summary>
        /// Test the property 'ObitStatus'
        /// </summary>
        [Test]
        public void ObitStatusTest()
        {
            // TODO unit test for the property 'ObitStatus'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Test]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'PartNumber'
        /// </summary>
        [Test]
        public void PartNumberTest()
        {
            // TODO unit test for the property 'PartNumber'
        }
        /// <summary>
        /// Test the property 'SerialNumberHash'
        /// </summary>
        [Test]
        public void SerialNumberHashTest()
        {
            // TODO unit test for the property 'SerialNumberHash'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Test]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'RootHash'
        /// </summary>
        [Test]
        public void RootHashTest()
        {
            // TODO unit test for the property 'RootHash'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Test]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'StructuredData'
        /// </summary>
        [Test]
        public void StructuredDataTest()
        {
            // TODO unit test for the property 'StructuredData'
        }

    }

}
