/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing LocalObitDocuments
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocalObitDocumentsTests
    {
        // TODO uncomment below to declare an instance variable for LocalObitDocuments
        //private LocalObitDocuments instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LocalObitDocuments
            //instance = new LocalObitDocuments();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LocalObitDocuments
        /// </summary>
        [Test]
        public void LocalObitDocumentsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LocalObitDocuments
            //Assert.IsInstanceOf(typeof(LocalObitDocuments), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Hashlink'
        /// </summary>
        [Test]
        public void HashlinkTest()
        {
            // TODO unit test for the property 'Hashlink'
        }

    }

}
