/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Obada.Client.Api;
using Obada.Client.Model;
using Obada.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Obada.Client.Test
{
    /// <summary>
    ///  Class for testing ObitHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObitHistoryTests
    {
        // TODO uncomment below to declare an instance variable for ObitHistory
        //private ObitHistory instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ObitHistory
            //instance = new ObitHistory();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ObitHistory
        /// </summary>
        [Test]
        public void ObitHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ObitHistory
            //Assert.IsInstanceOf(typeof(ObitHistory), instance);
        }


        /// <summary>
        /// Test the property 'ObitDid'
        /// </summary>
        [Test]
        public void ObitDidTest()
        {
            // TODO unit test for the property 'ObitDid'
        }
        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Test]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }
        /// <summary>
        /// Test the property 'OldValues'
        /// </summary>
        [Test]
        public void OldValuesTest()
        {
            // TODO unit test for the property 'OldValues'
        }
        /// <summary>
        /// Test the property 'NewValues'
        /// </summary>
        [Test]
        public void NewValuesTest()
        {
            // TODO unit test for the property 'NewValues'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
