/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Obada.Client.Client.OpenAPIDateConverter;

namespace Obada.Client.Model
{
    /// <summary>
    /// BlockChainObit
    /// </summary>
    [DataContract]
    public partial class BlockChainObit :  IEquatable<BlockChainObit>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BlockChainObit" /> class.
        /// </summary>
        /// <param name="rootHash">rootHash.</param>
        /// <param name="obitDid">obitDid.</param>
        public BlockChainObit(string rootHash = default(string), string obitDid = default(string))
        {
            this.RootHash = rootHash;
            this.ObitDid = obitDid;
        }

        /// <summary>
        /// Gets or Sets RootHash
        /// </summary>
        [DataMember(Name="root_hash", EmitDefaultValue=false)]
        public string RootHash { get; set; }

        /// <summary>
        /// Gets or Sets ObitDid
        /// </summary>
        [DataMember(Name="obit_did", EmitDefaultValue=false)]
        public string ObitDid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BlockChainObit {\n");
            sb.Append("  RootHash: ").Append(RootHash).Append("\n");
            sb.Append("  ObitDid: ").Append(ObitDid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BlockChainObit);
        }

        /// <summary>
        /// Returns true if BlockChainObit instances are equal
        /// </summary>
        /// <param name="input">Instance of BlockChainObit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BlockChainObit input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RootHash == input.RootHash ||
                    (this.RootHash != null &&
                    this.RootHash.Equals(input.RootHash))
                ) && 
                (
                    this.ObitDid == input.ObitDid ||
                    (this.ObitDid != null &&
                    this.ObitDid.Equals(input.ObitDid))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RootHash != null)
                    hashCode = hashCode * 59 + this.RootHash.GetHashCode();
                if (this.ObitDid != null)
                    hashCode = hashCode * 59 + this.ObitDid.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
