/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Obada.Client.Client.OpenAPIDateConverter;

namespace Obada.Client.Model
{
    /// <summary>
    /// Obit checksum
    /// </summary>
    [DataContract]
    public partial class Checksum :  IEquatable<Checksum>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Checksum" /> class.
        /// </summary>
        /// <param name="checksum">checksum.</param>
        public Checksum(string checksum = default(string))
        {
            this._Checksum = checksum;
        }

        /// <summary>
        /// Gets or Sets _Checksum
        /// </summary>
        [DataMember(Name="checksum", EmitDefaultValue=false)]
        public string _Checksum { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Checksum {\n");
            sb.Append("  _Checksum: ").Append(_Checksum).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Checksum);
        }

        /// <summary>
        /// Returns true if Checksum instances are equal
        /// </summary>
        /// <param name="input">Instance of Checksum to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Checksum input)
        {
            if (input == null)
                return false;

            return 
                (
                    this._Checksum == input._Checksum ||
                    (this._Checksum != null &&
                    this._Checksum.Equals(input._Checksum))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this._Checksum != null)
                    hashCode = hashCode * 59 + this._Checksum.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
