/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Obada.Client.Client.OpenAPIDateConverter;

namespace Obada.Client.Model
{
    /// <summary>
    /// LocalObit
    /// </summary>
    [DataContract]
    public partial class LocalObit :  IEquatable<LocalObit>, IValidatableObject
    {
        /// <summary>
        /// Represent available Obit statuses:   - FUNCTIONAL   - NON_FUNCTIONAL   - DISPOSED   - STOLEN   - DISABLED_BY_OWNER 
        /// </summary>
        /// <value>Represent available Obit statuses:   - FUNCTIONAL   - NON_FUNCTIONAL   - DISPOSED   - STOLEN   - DISABLED_BY_OWNER </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ObitStatusEnum
        {
            /// <summary>
            /// Enum FUNCTIONAL for value: FUNCTIONAL
            /// </summary>
            [EnumMember(Value = "FUNCTIONAL")]
            FUNCTIONAL = 1,

            /// <summary>
            /// Enum NONFUNCTIONAL for value: NON_FUNCTIONAL
            /// </summary>
            [EnumMember(Value = "NON_FUNCTIONAL")]
            NONFUNCTIONAL = 2,

            /// <summary>
            /// Enum DISPOSED for value: DISPOSED
            /// </summary>
            [EnumMember(Value = "DISPOSED")]
            DISPOSED = 3,

            /// <summary>
            /// Enum STOLEN for value: STOLEN
            /// </summary>
            [EnumMember(Value = "STOLEN")]
            STOLEN = 4,

            /// <summary>
            /// Enum DISABLEDBYOWNER for value: DISABLED_BY_OWNER
            /// </summary>
            [EnumMember(Value = "DISABLED_BY_OWNER")]
            DISABLEDBYOWNER = 5

        }

        /// <summary>
        /// Represent available Obit statuses:   - FUNCTIONAL   - NON_FUNCTIONAL   - DISPOSED   - STOLEN   - DISABLED_BY_OWNER 
        /// </summary>
        /// <value>Represent available Obit statuses:   - FUNCTIONAL   - NON_FUNCTIONAL   - DISPOSED   - STOLEN   - DISABLED_BY_OWNER </value>
        [DataMember(Name="obit_status", EmitDefaultValue=true)]
        public ObitStatusEnum ObitStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalObit" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LocalObit() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalObit" /> class.
        /// </summary>
        /// <param name="owner">Owner is the person/entity that owns the obit and the physical asset it represents. (required).</param>
        /// <param name="obitStatus">Represent available Obit statuses:   - FUNCTIONAL   - NON_FUNCTIONAL   - DISPOSED   - STOLEN   - DISABLED_BY_OWNER  (required).</param>
        /// <param name="manufacturer">Waiting more specific details from Rohi (required).</param>
        /// <param name="partNumber">Manufacturer provided. In cases where no part number is provided for the product, use model, or the most specific ID available from the manufacturer. MWCN2LL/A (an iPhone 11 Pro, Silver, 256GB, model A2160) (required).</param>
        /// <param name="serialNumber">Serial Number (required).</param>
        /// <param name="metadata">Get description from Rohi.</param>
        /// <param name="documents">To generate this link, take an SHA-256 hash of the document, and link to it as https://www.some-website.com?h1&#x3D;hash-of-document. Note this does not yet adhere to the hashlink standard. .</param>
        /// <param name="structuredData">Same as metadata but bigger. Key (string) &#x3D;&gt; Value (string) (hash per line sha256(key + value)).</param>
        /// <param name="modifiedOn">modifiedOn (required).</param>
        public LocalObit(string owner = default(string), ObitStatusEnum obitStatus = default(ObitStatusEnum), string manufacturer = default(string), string partNumber = default(string), string serialNumber = default(string), List<MetaDataRecord> metadata = default(List<MetaDataRecord>), List<LocalObitDocuments> documents = default(List<LocalObitDocuments>), List<StructureDataRecord> structuredData = default(List<StructureDataRecord>), int modifiedOn = default(int))
        {
            // to ensure "owner" is required (not null)
            if (owner == null)
            {
                throw new InvalidDataException("owner is a required property for LocalObit and cannot be null");
            }
            else
            {
                this.Owner = owner;
            }

            // to ensure "obitStatus" is required (not null)
            if (obitStatus == null)
            {
                throw new InvalidDataException("obitStatus is a required property for LocalObit and cannot be null");
            }
            else
            {
                this.ObitStatus = obitStatus;
            }

            // to ensure "manufacturer" is required (not null)
            if (manufacturer == null)
            {
                throw new InvalidDataException("manufacturer is a required property for LocalObit and cannot be null");
            }
            else
            {
                this.Manufacturer = manufacturer;
            }

            // to ensure "partNumber" is required (not null)
            if (partNumber == null)
            {
                throw new InvalidDataException("partNumber is a required property for LocalObit and cannot be null");
            }
            else
            {
                this.PartNumber = partNumber;
            }

            // to ensure "serialNumber" is required (not null)
            if (serialNumber == null)
            {
                throw new InvalidDataException("serialNumber is a required property for LocalObit and cannot be null");
            }
            else
            {
                this.SerialNumber = serialNumber;
            }

            // to ensure "modifiedOn" is required (not null)
            if (modifiedOn == null)
            {
                throw new InvalidDataException("modifiedOn is a required property for LocalObit and cannot be null");
            }
            else
            {
                this.ModifiedOn = modifiedOn;
            }

            this.Metadata = metadata;
            this.Documents = documents;
            this.StructuredData = structuredData;
        }

        /// <summary>
        /// Owner is the person/entity that owns the obit and the physical asset it represents.
        /// </summary>
        /// <value>Owner is the person/entity that owns the obit and the physical asset it represents.</value>
        [DataMember(Name="owner", EmitDefaultValue=true)]
        public string Owner { get; set; }


        /// <summary>
        /// Waiting more specific details from Rohi
        /// </summary>
        /// <value>Waiting more specific details from Rohi</value>
        [DataMember(Name="manufacturer", EmitDefaultValue=true)]
        public string Manufacturer { get; set; }

        /// <summary>
        /// Manufacturer provided. In cases where no part number is provided for the product, use model, or the most specific ID available from the manufacturer. MWCN2LL/A (an iPhone 11 Pro, Silver, 256GB, model A2160)
        /// </summary>
        /// <value>Manufacturer provided. In cases where no part number is provided for the product, use model, or the most specific ID available from the manufacturer. MWCN2LL/A (an iPhone 11 Pro, Silver, 256GB, model A2160)</value>
        [DataMember(Name="part_number", EmitDefaultValue=true)]
        public string PartNumber { get; set; }

        /// <summary>
        /// Serial Number
        /// </summary>
        /// <value>Serial Number</value>
        [DataMember(Name="serial_number", EmitDefaultValue=true)]
        public string SerialNumber { get; set; }

        /// <summary>
        /// Get description from Rohi
        /// </summary>
        /// <value>Get description from Rohi</value>
        [DataMember(Name="metadata", EmitDefaultValue=false)]
        public List<MetaDataRecord> Metadata { get; set; }

        /// <summary>
        /// To generate this link, take an SHA-256 hash of the document, and link to it as https://www.some-website.com?h1&#x3D;hash-of-document. Note this does not yet adhere to the hashlink standard. 
        /// </summary>
        /// <value>To generate this link, take an SHA-256 hash of the document, and link to it as https://www.some-website.com?h1&#x3D;hash-of-document. Note this does not yet adhere to the hashlink standard. </value>
        [DataMember(Name="documents", EmitDefaultValue=false)]
        public List<LocalObitDocuments> Documents { get; set; }

        /// <summary>
        /// Same as metadata but bigger. Key (string) &#x3D;&gt; Value (string) (hash per line sha256(key + value))
        /// </summary>
        /// <value>Same as metadata but bigger. Key (string) &#x3D;&gt; Value (string) (hash per line sha256(key + value))</value>
        [DataMember(Name="structured_data", EmitDefaultValue=false)]
        public List<StructureDataRecord> StructuredData { get; set; }

        /// <summary>
        /// Gets or Sets ModifiedOn
        /// </summary>
        [DataMember(Name="modified_on", EmitDefaultValue=true)]
        public int ModifiedOn { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LocalObit {\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  ObitStatus: ").Append(ObitStatus).Append("\n");
            sb.Append("  Manufacturer: ").Append(Manufacturer).Append("\n");
            sb.Append("  PartNumber: ").Append(PartNumber).Append("\n");
            sb.Append("  SerialNumber: ").Append(SerialNumber).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  Documents: ").Append(Documents).Append("\n");
            sb.Append("  StructuredData: ").Append(StructuredData).Append("\n");
            sb.Append("  ModifiedOn: ").Append(ModifiedOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LocalObit);
        }

        /// <summary>
        /// Returns true if LocalObit instances are equal
        /// </summary>
        /// <param name="input">Instance of LocalObit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LocalObit input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Owner == input.Owner ||
                    (this.Owner != null &&
                    this.Owner.Equals(input.Owner))
                ) && 
                (
                    this.ObitStatus == input.ObitStatus ||
                    (this.ObitStatus != null &&
                    this.ObitStatus.Equals(input.ObitStatus))
                ) && 
                (
                    this.Manufacturer == input.Manufacturer ||
                    (this.Manufacturer != null &&
                    this.Manufacturer.Equals(input.Manufacturer))
                ) && 
                (
                    this.PartNumber == input.PartNumber ||
                    (this.PartNumber != null &&
                    this.PartNumber.Equals(input.PartNumber))
                ) && 
                (
                    this.SerialNumber == input.SerialNumber ||
                    (this.SerialNumber != null &&
                    this.SerialNumber.Equals(input.SerialNumber))
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    this.Metadata != null &&
                    input.Metadata != null &&
                    this.Metadata.SequenceEqual(input.Metadata)
                ) && 
                (
                    this.Documents == input.Documents ||
                    this.Documents != null &&
                    input.Documents != null &&
                    this.Documents.SequenceEqual(input.Documents)
                ) && 
                (
                    this.StructuredData == input.StructuredData ||
                    this.StructuredData != null &&
                    input.StructuredData != null &&
                    this.StructuredData.SequenceEqual(input.StructuredData)
                ) && 
                (
                    this.ModifiedOn == input.ModifiedOn ||
                    (this.ModifiedOn != null &&
                    this.ModifiedOn.Equals(input.ModifiedOn))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Owner != null)
                    hashCode = hashCode * 59 + this.Owner.GetHashCode();
                if (this.ObitStatus != null)
                    hashCode = hashCode * 59 + this.ObitStatus.GetHashCode();
                if (this.Manufacturer != null)
                    hashCode = hashCode * 59 + this.Manufacturer.GetHashCode();
                if (this.PartNumber != null)
                    hashCode = hashCode * 59 + this.PartNumber.GetHashCode();
                if (this.SerialNumber != null)
                    hashCode = hashCode * 59 + this.SerialNumber.GetHashCode();
                if (this.Metadata != null)
                    hashCode = hashCode * 59 + this.Metadata.GetHashCode();
                if (this.Documents != null)
                    hashCode = hashCode * 59 + this.Documents.GetHashCode();
                if (this.StructuredData != null)
                    hashCode = hashCode * 59 + this.StructuredData.GetHashCode();
                if (this.ModifiedOn != null)
                    hashCode = hashCode * 59 + this.ModifiedOn.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
