/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Obada.Client.Client.OpenAPIDateConverter;

namespace Obada.Client.Model
{
    /// <summary>
    /// New Obit DID
    /// </summary>
    [DataContract]
    public partial class ObitDID :  IEquatable<ObitDID>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ObitDID" /> class.
        /// </summary>
        /// <param name="did">did.</param>
        public ObitDID(string did = default(string))
        {
            this.Did = did;
        }

        /// <summary>
        /// Gets or Sets Did
        /// </summary>
        [DataMember(Name="did", EmitDefaultValue=false)]
        public string Did { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ObitDID {\n");
            sb.Append("  Did: ").Append(Did).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ObitDID);
        }

        /// <summary>
        /// Returns true if ObitDID instances are equal
        /// </summary>
        /// <param name="input">Instance of ObitDID to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ObitDID input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Did == input.Did ||
                    (this.Did != null &&
                    this.Did.Equals(input.Did))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Did != null)
                    hashCode = hashCode * 59 + this.Did.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
