/*
 * OBADA API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: techops@obada.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Obada.Client.Client.OpenAPIDateConverter;

namespace Obada.Client.Model
{
    /// <summary>
    /// Request Obit Id payload
    /// </summary>
    [DataContract]
    public partial class RequestObitId :  IEquatable<RequestObitId>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestObitId" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RequestObitId() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestObitId" /> class.
        /// </summary>
        /// <param name="manufacturer">Manufacturer (Required) (required).</param>
        /// <param name="partNumber">Part Number (Required) (required).</param>
        /// <param name="serialNumber">Serial Number (Required) (required).</param>
        public RequestObitId(string manufacturer = default(string), string partNumber = default(string), string serialNumber = default(string))
        {
            // to ensure "manufacturer" is required (not null)
            if (manufacturer == null)
            {
                throw new InvalidDataException("manufacturer is a required property for RequestObitId and cannot be null");
            }
            else
            {
                this.Manufacturer = manufacturer;
            }

            // to ensure "partNumber" is required (not null)
            if (partNumber == null)
            {
                throw new InvalidDataException("partNumber is a required property for RequestObitId and cannot be null");
            }
            else
            {
                this.PartNumber = partNumber;
            }

            // to ensure "serialNumber" is required (not null)
            if (serialNumber == null)
            {
                throw new InvalidDataException("serialNumber is a required property for RequestObitId and cannot be null");
            }
            else
            {
                this.SerialNumber = serialNumber;
            }

        }

        /// <summary>
        /// Manufacturer (Required)
        /// </summary>
        /// <value>Manufacturer (Required)</value>
        [DataMember(Name="manufacturer", EmitDefaultValue=true)]
        public string Manufacturer { get; set; }

        /// <summary>
        /// Part Number (Required)
        /// </summary>
        /// <value>Part Number (Required)</value>
        [DataMember(Name="part_number", EmitDefaultValue=true)]
        public string PartNumber { get; set; }

        /// <summary>
        /// Serial Number (Required)
        /// </summary>
        /// <value>Serial Number (Required)</value>
        [DataMember(Name="serial_number", EmitDefaultValue=true)]
        public string SerialNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestObitId {\n");
            sb.Append("  Manufacturer: ").Append(Manufacturer).Append("\n");
            sb.Append("  PartNumber: ").Append(PartNumber).Append("\n");
            sb.Append("  SerialNumber: ").Append(SerialNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestObitId);
        }

        /// <summary>
        /// Returns true if RequestObitId instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestObitId to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestObitId input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Manufacturer == input.Manufacturer ||
                    (this.Manufacturer != null &&
                    this.Manufacturer.Equals(input.Manufacturer))
                ) && 
                (
                    this.PartNumber == input.PartNumber ||
                    (this.PartNumber != null &&
                    this.PartNumber.Equals(input.PartNumber))
                ) && 
                (
                    this.SerialNumber == input.SerialNumber ||
                    (this.SerialNumber != null &&
                    this.SerialNumber.Equals(input.SerialNumber))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Manufacturer != null)
                    hashCode = hashCode * 59 + this.Manufacturer.GetHashCode();
                if (this.PartNumber != null)
                    hashCode = hashCode * 59 + this.PartNumber.GetHashCode();
                if (this.SerialNumber != null)
                    hashCode = hashCode * 59 + this.SerialNumber.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
